### ISSUE TITLE
parsing fails

### ISSUE THREAD

**Issue by Noxfean** [pouya-eghbali/bean#2]
When trying to run any clio command I get the following error (Windows user btw) :

```
C:\Users\*username*\clio\node_modules\bean-parser\index.js:6
  rules.forEach(rule => {
        ^

TypeError: Cannot read property 'forEach' of null
    at beef (C:\Users\*username*\clio\node_modules\[4mbean-parser[24m\index.js:6:9)
    at Object.<anonymous> (C:\Users\*username*\clio\core\model.js:7:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1128:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:983:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:891:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1023:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\*username*\clio\core\parser.js:3:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1128:30)[39m
```

Discovered this together with @garritfra

**Comment by pouya-eghbali** [comment]
Do we still have this bug in v1.0.9?

**Comment by Noxfean** [comment]
> 
> 
> Do we still have this bug in v1.0.9?

Problem is fixed, I just don't get any output, @garritfra suggested that that problem might be clio internal.
